[project]
name = "break-reminder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ddgs>=9.16.0",
    "pillow>=12.3.0",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
[tool.ruff]
line-length = 80
[tool.pytest.ini_options]
pythonpath = ["."]